language: python
python:
  - "2.7"
  - "3.5"

install:
  - sudo apt-get update
  - sudo apt-get install libxml2-dev libxslt-dev zlib1g-dev
  - pip install stix
  - pip install stix-validator --pre
  - pip install lxml
  - pip install pep8

script: 
  - find . -name \*.py -exec pep8 --ignore=E501 {} +
  - ./test_idioms.sh

branches:
  only:
    - master

notifications:
  email:
    - stix-commits-list@lists.mitre.org

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fbfa85a0bb8108ad060
    on_success: change
    on_failure: always
    on_start: false

